#Settings
title: Welcome to my portfolio.
email: jacob.emerson07@gmail.com
description: "Portfolio website for Jacob Emerson - Data Science Student at UC Irvine."
baseurl: ""
url: "http://jacob-emerson.me"


theme: jekyll-theme-cayman


# Portfolio Website In Progress:
### What I need for the next update:
* Change the Title
* See if it's possible to de-link the title of the page from the title at the top of the screen.
* Add another webpage and redirect.
